### PR TITLE
Orders don't require bank account number anymore

### PR DESCRIPTION
**Pull request by savatarko**

### CODE REVIEW

**Review by Kovelja009 — APPROVED** [review]
/lgtm

**Comment by ghost** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/RAF-SI-2023/Banka-1-Backend/pull/325#issuecomment-2189138673" title="Approved">ijevtic</a>*, *<a href="https://github.com/RAF-SI-2023/Banka-1-Backend/pull/325#" title="Author self-approved">savatarko</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=RAF-SI-2023%2FBanka-1-Backend).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/RAF-SI-2023/Banka-1-Backend/blob/sprint-9/OWNERS)~~ [ijevtic]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
