### PR TITLE
Sprint 9- physical and legal persons can create orders

### PR DESCRIPTION
**Pull request by savatarko**
People with a company bank account can use it to buy stock forex and future, with a regular account customers can only buy stocks.

### CODE REVIEW

**Comment by ijevtic** [comment]
integracioni?

**Comment by savatarko** [comment]
> integracioni?

nisam napisao jer valjda tisma sredjuje da radi (provalili smo sta je problem), jos nije uradio pr kasnije cu dodati kada bude mergovano

**Review by Kovelja009 — APPROVED** [review]
/lgtm

**Pull request merged**
