### PR TITLE
ForexService and OptionsService tests also fixed mapper for exchangeName

### PR DESCRIPTION
**Pull request by Kovelja009**
Added tests for `ForexServiceImplTest` with following coverage: 

image

Commented out  one **printStackTrace** because I need it to fail in the tests, but not want to show stackTrace in tests.

Also added `@Disabled` annotation for the `ListingStockServiceImplTest` until they get fixed.

### CODE REVIEW

**Comment by ijevtic** [comment]
jel ovo gotovo ili ujutru?

**Comment by Kovelja009** [comment]
Also added tests for `OptionsServiceImpl` with following coverage: 

image

Added one `getter` in service, so I could test it easier. All tests are passing, but some throws exception (which is intended behavior).

Branches coverage isn't > 80% because it wasn't easy to cover all cases, but instruction coverage is > 80%, which I hope is okay.

**Review by savatarko — CHANGES_REQUESTED** [review]
promeniti testove za koje se ocekuje exception umesto try catch da bude assertThrows, jer treba da se proveri da baca gresku kada nije okej

**Comment by Kovelja009** [comment]
Ali ja nigde ne hvatam exception, svaka funkcija u servisima ima svoj try-catch blok, tako da ja ni ne mogu da uhvatim grešku.

**Pull request merged**
